name: "Docker Composite Private Registry"
description: "Test Docker composite action with private registry"

inputs:
  image:
    description: "Docker image name"
    required: false
    default: "ubuntu"

runs:
  using: "composite"
  steps:
    - name: Docker run
      shell: bash
      run: docker run --rm --entrypoint /bin/sh ${{ inputs.image }} -c 'echo "Hello from Docker container"'
