name: "Docker Image Private Registry"
description: "Test Docker Image action with private registry"
runs:
  using: "docker"
  image: "docker://ghcr.io/a-magdy/ubuntu"
  args:
    - "/bin/sh"
    - "-c"
    - echo "Running from inside the Docker container"
