name: "Docker Registry Login"
description: "Logs in to a Docker registry using provided credentials."

inputs:
  registry:
    description: "Docker registry URL"
    required: false
    default: "docker.io"
  username:
    description: "ACR username"
    required: true
  password:
    description: "ACR password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
