name: Test Docker-in-Docker (DinD)

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_REGISTRY_USER: a-magdy

jobs:
  dind-run-image-fails:
    name: DinD - Image (Fails)
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/a-magdy/dind
      credentials:
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Image Action
        uses: a-magdy/test-gh-docker-actions/test-gh-docker/image@main

  dind-run-dockerfile-fails:
    name: DinD - Dockerfile (Fails)
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/a-magdy/dind
      credentials:
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dockerfile Action
        uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main

  dind-composite-action-succeeds:
    name: DinD - Composite (Succeeds)
    runs-on: ubuntu-latest
    needs: [dind-run-image-fails, dind-run-dockerfile-fails]
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/a-magdy/dind
      credentials:
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - uses: actions/checkout@v4

      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test image
        shell: bash
        run: docker run --rm ghcr.io/a-magdy/ubuntu echo "Hello from Docker in DinD"
