name: Test Dockerfile Action

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_REGISTRY_USER: a-magdy

jobs:
  run-dockerfile-action-fails:
    name: Dockerfile (Fails)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main
        continue-on-error: true

  run-dockerfile-action-succeeds:
    name: Dockerfile (Succeeds)
    runs-on: ubuntu-latest
    needs: run-dockerfile-action-fails
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Run Dockerfile Action
        uses: ./test-gh-docker/dockerfile
