name: Test Image Action

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_REGISTRY_USER: a-magdy

jobs:
  run-image-action-fails:
    name: Image (Fails)
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/image@main

  run-image-action-succeeds:
    name: Image (Succeeds)
    runs-on: ubuntu-latest
    needs: run-image-action-fails
    permissions:
      contents: read
      packages: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: docker pull ghcr.io/a-magdy/ubuntu

      - uses: ./test-gh-docker/image
