name: Test GH Docker Actions (GHCR)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_REGISTRY_USER: a-magdy

jobs:
  run-composite-action:
    name: Run Composite Action (Succeeds)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/composite@main
        with:
          image: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REGISTRY_USER }}/ubuntu

  run-dockerfile-action-fail:
    name: Run Dockerfile Action (Fails)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main
    continue-on-error: true

  run-dockerfile-action-success:
    name: Run Dockerfile Action (Succeeds)
    runs-on: ubuntu-latest
    needs: run-dockerfile-action-fail
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Run Dockerfile Action
        uses: ./test-gh-docker/dockerfile

  run-image-action-fail:
    name: Run Image Action (Fails)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/image@main
    continue-on-error: true

  run-image-action-success:
    name: Run Image Action (Succeeds)
    runs-on: ubuntu-latest
    needs: run-image-action-fail
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: docker pull ghcr.io/a-magdy/ubuntu

      - uses: ./test-gh-docker/image

  dind-run-image:
    name: DinD Run Image (Fails)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/a-magdy/dind
      credentials:
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - name: Docker Registry Login
        uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Image Action
        uses: a-magdy/test-gh-docker-actions/test-gh-docker/image@main
    continue-on-error: true
  dind-run-dockerfile:
    name: DinD Run Dockerfile (Fails)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/a-magdy/dind
      credentials:
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - name: Docker Registry Login
        uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dockerfile Action
        uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main
    continue-on-error: true
  dind-composite-action:
    name: DinD Composite Action (Succeeds)
    runs-on: ubuntu-latest
    needs: [dind-run-image, dind-run-dockerfile]
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/a-magdy/dind
      credentials:
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - uses: actions/checkout@v4

      - name: Docker Registry Login
        uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test image
        shell: bash
        run: docker run --rm ghcr.io/a-magdy/ubuntu echo "Hello from Docker in DinD"
