name: Test GH Docker Actions (ACR)

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

env:
  TESTGH_ACR_REGISTRY: testgh.azurecr.io
  TESTGH_ACR_USERNAME: testgh

jobs:
  run-composite-action:
    name: Run Composite Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/composite@main

  run-dockerfile-action-fail:
    name: Run Dockerfile Action (Fails)
    runs-on: ubuntu-latest
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main
    continue-on-error: true

  run-dockerfile-action-success:
    name: Run Dockerfile Action
    runs-on: ubuntu-latest
    needs: run-dockerfile-action-fail
    permissions:
      contents: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - uses: actions/checkout@v4

      - name: Run Dockerfile Action
        uses: ./test-gh-docker/dockerfile

  run-image-action-fail:
    name: Run Image Action (Fails)
    runs-on: ubuntu-latest
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/image@main
    continue-on-error: true

  run-image-action-success:
    name: Run Image Action
    runs-on: ubuntu-latest
    needs: run-image-action-fail
    permissions:
      contents: read
    steps:
      - uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - uses: actions/checkout@v4

      - run: docker pull testgh.azurecr.io/test

      - uses: ./test-gh-docker/image

  dind-run-image:
    name: DinD Run Image (Fail)
    runs-on: ubuntu-latest
    container:
      image: testgh.azurecr.io/dind:latest
      credentials:
        username: ${{ env.TESTGH_ACR_USERNAME }}
        password: ${{ secrets.TESTGH_ACR_PASSWORD }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - name: Docker Registry Login
        uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - name: Run Image Action (Fail)
        uses: a-magdy/test-gh-docker-actions/test-gh-docker/image@main
    continue-on-error: true
  dind-run-dockerfile:
    name: DinD Run Dockerfile (Fail)
    runs-on: ubuntu-latest
    container:
      image: testgh.azurecr.io/dind:latest
      credentials:
        username: ${{ env.TESTGH_ACR_USERNAME }}
        password: ${{ secrets.TESTGH_ACR_PASSWORD }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - name: Docker Registry Login
        uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - name: Run Dockerfile Action (Fail)
        uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main
    continue-on-error: true
  dind-composite-action:
    name: DinD Composite Action
    runs-on: ubuntu-latest
    needs: [dind-run-image, dind-run-dockerfile]
    container:
      image: testgh.azurecr.io/dind:latest
      credentials:
        username: ${{ env.TESTGH_ACR_USERNAME }}
        password: ${{ secrets.TESTGH_ACR_PASSWORD }}
      options: --privileged # For Docker-in-Docker if needed
    steps:
      - uses: actions/checkout@v4

      - name: Docker Registry Login
        uses: a-magdy/test-gh-docker-actions/common/docker-registry-login@main
        with:
          registry: ${{ env.TESTGH_ACR_REGISTRY }}
          username: ${{ env.TESTGH_ACR_USERNAME }}
          password: ${{ secrets.TESTGH_ACR_PASSWORD }}

      - name: Test image
        shell: bash
        run: docker run --rm testgh.azurecr.io/test echo "Hello from Docker in DinD"
