name: Test All Docker Actions

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-composite:
    name: Composite
    uses: ./.github/workflows/test-composite-action.yml
    secrets: inherit

  test-dockerfile:
    name: Dockerfile
    uses: ./.github/workflows/test-dockerfile-action.yml
    secrets: inherit

  test-image:
    name: Image
    uses: ./.github/workflows/test-image-action.yml
    secrets: inherit

  test-dind:
    name: Dind
    uses: ./.github/workflows/test-dind.yml
    secrets: inherit

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [test-composite, test-dockerfile, test-image, test-dind]
    if: always()
    steps:
      - name: Check results
        run: |
          {
            echo "## Test Results Summary"
            echo "| Test Type | Status |"
            echo "|-----------|--------|"
            echo "| Composite | ${{ needs.test-composite.result }} |"
            echo "| Dockerfile | ${{ needs.test-dockerfile.result }} |"
            echo "| Image | ${{ needs.test-image.result }} |"
            echo "| DinD | ${{ needs.test-dind.result }} |"
          } >> "$GITHUB_STEP_SUMMARY"
